/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author redoy
 */
public class AMalBickriStock extends javax.swing.JFrame {

    /**
     * Creates new form totalProduct
     */
    public AMalBickriStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        printLabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xx = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dateField = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        pNameField = new javax.swing.JComboBox();
        idL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        quantityField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printLabel.setBackground(new java.awt.Color(204, 204, 204));

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nam:", "Poriman / fit", "Date", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockTableMouseClicked(evt);
            }
        });
        stockTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stockTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(stockTable);
        if (stockTable.getColumnModel().getColumnCount() > 0) {
            stockTable.getColumnModel().getColumn(0).setResizable(false);
            stockTable.getColumnModel().getColumn(1).setResizable(false);
            stockTable.getColumnModel().getColumn(2).setResizable(false);
            stockTable.getColumnModel().getColumn(3).setResizable(false);
            stockTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Bikri Maler Stock");

        totalField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Total");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("/Fit");

        xx.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xx.setText("XX");

        javax.swing.GroupLayout printLabelLayout = new javax.swing.GroupLayout(printLabel);
        printLabel.setLayout(printLabelLayout);
        printLabelLayout.setHorizontalGroup(
            printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printLabelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLabelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLabelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLabelLayout.createSequentialGroup()
                        .addComponent(xx, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(331, 331, 331))))
        );
        printLabelLayout.setVerticalGroup(
            printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xx, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printLabelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(printLabelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 34, Short.MAX_VALUE))
        );

        jPanel2.add(printLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 740, 590));

        jLabel2.setText("Product Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 30));

        jLabel1.setText("Date");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, 30));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 100, 30));

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 110, 30));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, 30));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 100, 30));

        dateField.setBackground(new java.awt.Color(204, 204, 204));
        dateField.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 230, 30));

        jLabel6.setText("Poriman ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("/Fit");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 60, 30));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 110, 30));

        pNameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pNameField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Product", "3\"/4 Boalder Banga", "3\"/4 Vutu Vanga", "3\"/4 Dawn 16 Mili", "1\"/2 Vanga", "5\"/10 Vanga", "Lal Vutu", "Lal Boalder", "Sada Vutu", "Sada Boalder", "Lal Single", "Sada Single", "Cuna", "All" }));
        pNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(pNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 230, 30));

        idL.setText("id");
        jPanel2.add(idL, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 110, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 28, 220, -1));

        quantityField.setBackground(new java.awt.Color(204, 204, 204));
        quantityField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantityField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityField.setBorder(null);
        jPanel1.add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 220, 30));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jMenu2.setText("                                                                  ");
        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(204, 0, 204));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu4.setText("Sale Product");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("                     ");
        jMenuBar1.add(jMenu6);

        jMenu5.setText("Stock");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        jMenuItem1.setText("    Mal Kiner Stock    ");
        jMenuItem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem3.setText("  Mal Bickri Stock            ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        jMenu7.setBackground(new java.awt.Color(255, 255, 255));
        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setText("                  ");
        jMenuBar1.add(jMenu7);

        jMenu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu9.setText("   Customer Stock       ");
        jMenu9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu8.setText("               ");
        jMenuBar1.add(jMenu8);

        jMenu11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu11.setText("Employee Details");
        jMenu11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem2.setText("Add New Employee");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem2);

        jMenuItem4.setText("Salary");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem4);

        jMenuBar1.add(jMenu11);

        jMenu10.setText("                ");
        jMenuBar1.add(jMenu10);

        jMenu12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu12.setText("Owener Details");
        jMenu12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenu12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu12ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu12);

        jMenu17.setText("  ALL INFO    ");
        jMenu17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu17MouseClicked(evt);
            }
        });
        jMenu17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu17ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu17);

        jMenu18.setText("           Print                ");
        jMenu18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu18MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu18);

        jMenu15.setBorder(null);
        jMenu15.setText("-");
        jMenu15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu15);

        jMenu16.setBorder(null);
        jMenu16.setForeground(new java.awt.Color(204, 0, 0));
        jMenu16.setText("X");
        jMenu16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu16MouseClicked(evt);
            }
        });
        jMenu16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu16ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu16);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
                String datex = ((JTextField) dateField.getDateEditor().getUiComponent()).getText();

        if(quantityField.getText().equals("")){
        
        JOptionPane.showMessageDialog(null, "Enter Amount.....!");
        
        }
        else if(datex.equals("")){
        JOptionPane.showMessageDialog(null, "Enter Date");
        }else{

        String s = new String("Product");
        String s1 = new String("");
        String a = pNameField.getSelectedItem().toString();
        String am = quantityField.getText();
        if (s.equals(a) || s1.equals(am)) {

            try {
                JOptionPane.showMessageDialog(null, "Select Product Name For Search....!");
                String name = pNameField.getSelectedItem().toString();
                System.out.println(name);
                String amount = quantityField.getText();
                // this.dispose();
                DataBase db = new DataBase();
                //       db.ProductStock2(name,amount);
            } catch (SQLException ex) {
                Logger.getLogger(AMalBickriStock.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
               
            double temAM=Double.parseDouble(quantityField.getText());
            if(temAM>1){
                
            try {
                String name = pNameField.getSelectedItem().toString();
                System.out.println(name);
                
             String amount = quantityField.getText();
             
             
                String date = ((JTextField) dateField.getDateEditor().getUiComponent()).getText();
                ///this.dispose();
                DataBase db = new DataBase();
                db.ProductStock(name, amount, date);
                //  JOptionPane.showMessageDialog(null,"Sorry");
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Sorry..");
            }

            }else{
            JOptionPane.showMessageDialog(null, "Enter Right Amount....");
            
            }
        }


}

    }//GEN-LAST:event_addBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String s = new String("Product");
        String s1 = new String("All");
        String a = pNameField.getSelectedItem().toString();
        String am = quantityField.getText();
        if (s.equals(a)) {

            JOptionPane.showMessageDialog(null, "Select Product Name...!");
        } else if (s1.equals(a)) {
            
            try {
                pNameField.setSelectedItem(s1);
                String all = pNameField.getSelectedItem().toString();
                //String amount = quantityField.getText();
                 this.dispose();
                DataBase db = new DataBase();
                    db.showAllProduct(all);
            } catch (SQLException ex) {
                Logger.getLogger(AMalBickriStock.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else{
         try {
                
                String name = pNameField.getSelectedItem().toString();
                //String amount = quantityField.getText();
                 this.dispose();
                DataBase db = new DataBase();
                db.showSelectProduct(name);
            } catch (SQLException ex) {
                Logger.getLogger(AMalBickriStock.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
           DefaultTableModel model = (DefaultTableModel) stockTable.getModel();
            model.setRowCount(0);
            quantityField.setText(null);
            ((JTextField) dateField.getDateEditor().getUiComponent()).setText(null);
            pNameField.setSelectedItem("Product");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            
            
            String id=idL.getText();
             String name= pNameField.getSelectedItem().toString();
             String amount=quantityField.getText();
            String ab= xx.getText();
             
             double am=Double.parseDouble(amount);
             String date=((JTextField) dateField.getDateEditor().getUiComponent()).getText();
            //  this.dispose();
              if(ab.equals("") ||ab.equals("All") ){
           JOptionPane.showMessageDialog(null, "Sorry You Don't Delete This Item....!");
           
           
           }else if(ab.equals("0")){
               
                 DataBase ob=new DataBase();
            ob.updateDataAZeroDelete(id,name,amount,date);
             
             }
             
             
             else {
                DataBase ob=new DataBase();
            ob.updateData(id,name,amount,date);
             
             }
         
            
            
            /* ******Selected Row PASS*************/
            
            //  page.setVisible(true);
            
            
            
            
            
            
            /*
            DefaultTableModel m = (DefaultTableModel) memoTable.getModel();
            for (int i = 0; i < m.getRowCount(); i++) {
            String s = m.getValueAt(i, 0).toString();
            String s1 = m.getValueAt(i, 1).toString();
            String s2 = m.getValueAt(i, 2).toString();
            String s3 = m.getValueAt(i, 3).toString();
            String s4 = m.getValueAt(i, 4).toString();
            String s5 = serialField.getText();
            String s6=nameField.getText();
            String s7=addressField.getText();
            String s8=mobileField.getText();
            String s9=dateField.getDateFormatString();
            String sT=totalField.getText();
            System.out.println(s + " " + s1 + " " + s2 + " " + s3 + " " + s4 + " " + s5);
            sold db = new sold();
            db.soldP(s, s1, s2, s3, s4, s5,s6,s7,s8,s9,sT);
            db.setVisible(true);
            }
            
            
            
            /*
            
            
            *******Selected Row PASS***************
            
            
            
            TableModel model=memoTable.getModel();
            int index[]=memoTable.getSelectedRows();
            Object[] row=new Object[5];
            sold page=new sold();
            
            // DefaultTableModel model2=page.memoTable.getModel();
            DefaultTableModel m2 = (DefaultTableModel) page.memoTable.getModel();
            
            for(int i=0;i<index.length;i++){
            
            row[0]=model.getValueAt(index[i], 0);
            row[1]=model.getValueAt(index[i], 1);
            row[2]=model.getValueAt(index[i], 2);
            row[3]=model.getValueAt(index[i], 3);
            row[4]=model.getValueAt(index[i], 4);
            m2.addRow(row);
            
            
            
            }
            page.setVisible(true);
            
            
            */
            
            
            
            /*
            DefaultTableModel m = (DefaultTableModel) memoTable.getModel();
            for (int i = 0; i < m.getRowCount(); i++) {
            String s = m.getValueAt(i, 0).toString();
            String s1 = m.getValueAt(i, 1).toString();
            String s2 = m.getValueAt(i, 2).toString();
            String s3 = m.getValueAt(i, 3).toString();
            String s4 = m.getValueAt(i, 4).toString();
            String s5 = serialField.getText();
            String s6=nameField.getText();
            String s7=addressField.getText();
            String s8=mobileField.getText();
            String s9=dateField.getDateFormatString();
            String sT=totalField.getText();
            System.out.println(s + " " + s1 + " " + s2 + " " + s3 + " " + s4 + " " + s5);
            sold db = new sold();
            db.soldP(s, s1, s2, s3, s4, s5,s6,s7,s8,s9,sT);
            db.setVisible(true);
            }
            */
        } catch (SQLException ex) {
            Logger.getLogger(AMalBickriStock.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            String ab=xx.getText();
            
            
            // TODO add your handling code here:
            String id=idL.getText();
            String name= pNameField.getSelectedItem().toString();
            String amount=quantityField.getText();
            String date=((JTextField) dateField.getDateEditor().getUiComponent()).getText();
            //  this.dispose();
                    if(ab.equals("All")){
                    
                    JOptionPane.showMessageDialog(null, "SORYY DON'T DELETE THIS ITEM....!");
                    }else{
                         DataBase ob=new DataBase();
                        ob.updateMainDate(id,name,amount,date);
 
                    
                    }
            
            /*
            
            
            *******Selected Row PASS***************
            
            
            
            TableModel model=memoTable.getModel();
            int index[]=memoTable.getSelectedRows();
            Object[] row=new Object[5];
            sold page=new sold();
            
            // DefaultTableModel model2=page.memoTable.getModel();
            DefaultTableModel m2 = (DefaultTableModel) page.memoTable.getModel();
            
            for(int i=0;i<index.length;i++){
            
            row[0]=model.getValueAt(index[i], 0);
            row[1]=model.getValueAt(index[i], 1);
            row[2]=model.getValueAt(index[i], 2);
            row[3]=model.getValueAt(index[i], 3);
            row[4]=model.getValueAt(index[i], 4);
            m2.addRow(row);
            
            
            
            }
            page.setVisible(true);
            
            
            */
            
            
            
            /*
            DefaultTableModel m = (DefaultTableModel) memoTable.getModel();
            for (int i = 0; i < m.getRowCount(); i++) {
            String s = m.getValueAt(i, 0).toString();
            String s1 = m.getValueAt(i, 1).toString();
            String s2 = m.getValueAt(i, 2).toString();
            String s3 = m.getValueAt(i, 3).toString();
            String s4 = m.getValueAt(i, 4).toString();
            String s5 = serialField.getText();
            String s6=nameField.getText();
            String s7=addressField.getText();
            String s8=mobileField.getText();
            String s9=dateField.getDateFormatString();
            String sT=totalField.getText();
            System.out.println(s + " " + s1 + " " + s2 + " " + s3 + " " + s4 + " " + s5);
            sold db = new sold();
            db.soldP(s, s1, s2, s3, s4, s5,s6,s7,s8,s9,sT);
            db.setVisible(true);
            }
            */
        } catch (SQLException ex) {
            Logger.getLogger(AMalBickriStock.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stockTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockTableKeyPressed
        // TODO add your handling code here:
        
        
          
        
        
        
        
    }//GEN-LAST:event_stockTableKeyPressed

    private void stockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTableMouseClicked
        // TODO add your handling code here:
        
        
          
           /* ******Selected Row PASS*************/
            
            
            
            TableModel model=stockTable.getModel();
            int index[]=stockTable.getSelectedRows();
            Object[] row=new Object[5];
        // AtotalProductStock page=new AtotalProductStock();
            
          //DefaultTableModel model2=page.memoTable.getModel();
          //DefaultTableModel m2 = (DefaultTableModel).stockTable.getModel();
            
            for(int i=0;i<index.length;i++){
            
            row[0]=model.getValueAt(index[i], 0);
            
            row[1]=model.getValueAt(index[i], 1);
              pNameField.setSelectedItem((String)row[1]);
                System.out.println("OOKK"+(String)row[1]);
                pNameField.setSelectedItem("AA<A:LsdfwesdZDVZ");
            row[2]=model.getValueAt(index[i], 2);
            quantityField.setText((String) row[2]);
            double am=Double.parseDouble((String) row[2]);
            row[3]=model.getValueAt(index[i], 3);
            ((JTextField) dateField.getDateEditor().getUiComponent()).setText((String) row[3]);
            row[4]=model.getValueAt(index[i], 4);
             idL.setText((String) row[4]);
              String ab=xx.getText();
            System.out.println("ID..."+(String) row[4]);
            if(am==0){
            xx.setText("0");
            
            }else{
                
            }
            
            
            
            
            }
          
        
        
    }//GEN-LAST:event_stockTableMouseClicked

    private void pNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameFieldActionPerformed
        

// TODO add your handling code here:
    }//GEN-LAST:event_pNameFieldActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
    try {
            // TODO add your handling code here:
            this.dispose();
            DataBase x=new DataBase();
            x.searcgMemeoID();
             //  x.searcgMemeoID();
            
           // cashMemo ob = new cashMemo();
           // ob.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(allInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        BtotalMalKinartStock ob = new BtotalMalKinartStock();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

/*
                this.dispose();
        AMalBickriStock ob = new AMalBickriStock();
        ob.setVisible(true);

        */

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked

       
        
        try {
            this.dispose();
            CcustomerStock ob = new CcustomerStock();
            ob.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AMalBickriStock.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        

    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        newEmployee ob = new newEmployee();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        // TODO add your handling code here:
        
        
        
        
        this.dispose();
        DAmalikerJomaKoroch ob=new DAmalikerJomaKoroch();
        
        
        ob.setVisible(true);
       
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu18MouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {

                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.70, 1.24);
                printLabel.print(g2);
                return Printable.PAGE_EXISTS;

            }

        });
        boolean ok = job.printDialog();
        if (ok) {

            try {
                job.print();
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jMenu18MouseClicked

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
        // TODO add your handling code here:
        this.setState(allInfo.ICONIFIED);
    }//GEN-LAST:event_jMenu15MouseClicked

    private void jMenu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu16MouseClicked

        System.exit(WIDTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu16MouseClicked

    private void jMenu16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu16ActionPerformed

    private void jMenu17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu17MouseClicked
        // TODO add your handling code here:
  
        this.dispose();
        allInfo ob=new allInfo();
        ob.setVisible(true);
        
        
    }//GEN-LAST:event_jMenu17MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        this.dispose();
        AESalaryPage ob=new  AESalaryPage();
        ob.setVisible(true);
        

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        AESalaryPage ob=new  AESalaryPage();
        ob.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenu17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu17ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu17ActionPerformed

    private void jMenu12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu12ActionPerformed
        // TODO add your handling code here:
        
        



// TODO add your handling code here:
    }//GEN-LAST:event_jMenu12ActionPerformed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        // TODO add your handling code here:

        


// TODO add your handling code here:
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

        // TODO add your handling code here:
        

// TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AMalBickriStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AMalBickriStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AMalBickriStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AMalBickriStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AMalBickriStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JLabel idL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox pNameField;
    private javax.swing.JPanel printLabel;
    private javax.swing.JTextField quantityField;
    javax.swing.JTable stockTable;
    javax.swing.JTextField totalField;
    javax.swing.JLabel xx;
    // End of variables declaration//GEN-END:variables

   
}
