/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/**
 *
 * @author redoy
 */
public class BtotalMalKinartStock extends javax.swing.JFrame {

    /**
     * Creates new form totalProduct
     */
    public BtotalMalKinartStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        printLabel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        totalF = new javax.swing.JTextField();
        aDate = new com.toedter.calendar.JDateChooser();
        bDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pNameField = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        dateField = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c_nam = new javax.swing.JTextField();
        c_no = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        c_phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        calan_no = new javax.swing.JTextField();
        gari_no = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        driver = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        searchF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idL = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mal Kinar Stock");

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Maler Nam", "Poriman", "Customer Nam", "Customer No", "Customer Phone", "Driver", "Calan No:", "Truck/Lory", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stockTable);

        jLabel10.setText("Total Poriman");

        aDate.setDateFormatString("yyyy-MM-dd");

        bDate.setDateFormatString("yyyy-MM-dd");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("From");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("To");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Shajala Stone Crusher");

        javax.swing.GroupLayout printLabelLayout = new javax.swing.GroupLayout(printLabel);
        printLabel.setLayout(printLabelLayout);
        printLabelLayout.setHorizontalGroup(
            printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLabelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addGroup(printLabelLayout.createSequentialGroup()
                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printLabelLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(printLabelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aDate, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(printLabelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(printLabelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        printLabelLayout.setVerticalGroup(
            printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(aDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(printLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 890, 640));

        pNameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pNameField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Product", "3\"/4 Boalder Banga", "3\"/4 Vutu Vanga", "3\"/4 Dawn 16 Mili", "1\"/2 Vanga", "5\"/10 Vanga", "Lal Vutu", "Lal Boalder", "Sada Vutu", "Sada Boalder", "Lal Single", "Sada Single", "Cuna", "All" }));
        pNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(pNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 30));

        jLabel2.setText("Product Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 30));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 100, 30));

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 110, 30));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 110, 30));

        jLabel1.setText("Poriman ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 30));

        quantityField.setBackground(new java.awt.Color(204, 204, 204));
        quantityField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantityField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityField.setBorder(null);
        jPanel2.add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 190, 30));

        dateField.setDateFormatString("yyyy-MM-dd");
        dateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 30));

        jLabel3.setText("Date:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 30));

        jLabel7.setText("Customer Nam");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 30));

        c_nam.setBackground(new java.awt.Color(204, 204, 204));
        c_nam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c_nam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_nam.setBorder(null);
        jPanel2.add(c_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 190, 30));

        c_no.setBackground(new java.awt.Color(204, 204, 204));
        c_no.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_no.setBorder(null);
        jPanel2.add(c_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 190, 30));

        jLabel8.setText("Customer No");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 30));

        c_phone.setBackground(new java.awt.Color(204, 204, 204));
        c_phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_phone.setBorder(null);
        jPanel2.add(c_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 190, 30));

        jLabel6.setText("Customer Phone");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, 30));

        calan_no.setBackground(new java.awt.Color(204, 204, 204));
        calan_no.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calan_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        calan_no.setBorder(null);
        jPanel2.add(calan_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 190, 30));

        gari_no.setBackground(new java.awt.Color(204, 204, 204));
        gari_no.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gari_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gari_no.setBorder(null);
        jPanel2.add(gari_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 190, 30));

        jLabel11.setText("Gari Number");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 100, 30));

        driver.setBackground(new java.awt.Color(204, 204, 204));
        driver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        driver.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        driver.setBorder(null);
        jPanel2.add(driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 190, 30));

        jLabel9.setText("Driver");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 530, -1, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 140, 30));
        jPanel2.add(searchF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 30));

        jLabel12.setText("Calan No:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, 30));
        jPanel2.add(idL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 40, 40));
        jPanel2.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 74, 60, 0));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jMenu2.setText("                                                                                                     ");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(204, 0, 204));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu4.setText("Sale Product");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("                   ");
        jMenuBar1.add(jMenu6);

        jMenu5.setText("Stock");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        jMenuItem1.setText("    Mal Kiner Stock    ");
        jMenuItem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem3.setText("  Mal Bickri Stock            ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        jMenu7.setBackground(new java.awt.Color(255, 255, 255));
        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setText("                  ");
        jMenuBar1.add(jMenu7);

        jMenu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu9.setText("   Customer Stock       ");
        jMenu9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu8.setText("                    ");
        jMenuBar1.add(jMenu8);

        jMenu11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu11.setText("Employee Details");
        jMenu11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem2.setText("Add New Employee");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem2);

        jMenuItem4.setText("Salary");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem4);

        jMenuBar1.add(jMenu11);

        jMenu10.setText("    ALL INFO    ");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        jMenu12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu12.setText("Owener Details");
        jMenu12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu12);

        jMenu18.setText("      Print       ");
        jMenu18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu18MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu18);

        jMenu15.setBorder(null);
        jMenu15.setText("-");
        jMenu15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu15);

        jMenu16.setBorder(null);
        jMenu16.setForeground(new java.awt.Color(204, 0, 0));
        jMenu16.setText("X");
        jMenu16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu16MouseClicked(evt);
            }
        });
        jMenu16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu16ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu16);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String s = new String("Product");
        String s2 = new String("All");
        String s1 = new String("");
        String a = pNameField.getSelectedItem().toString();
        String am = quantityField.getText();
        if (s.equals(a) || s1.equals(am) || s2.equals(am)) {

            JOptionPane.showMessageDialog(null, "Sorry....!");
        } else {

            try {
                String name = pNameField.getSelectedItem().toString();
                System.out.println(name);
                String amount = quantityField.getText();
                String date = ((JTextField) dateField.getDateEditor().getUiComponent()).getText();
                String cusNm = c_nam.getText();
                String cusNo = c_no.getText();
                String cusPhone = c_phone.getText();
                String driNm = driver.getText();
                String calan = calan_no.getText();
                String zip = gari_no.getText();
                ///this.dispose();
                DataBase db = new DataBase();
                db.BAllStock(name, amount, date, cusNm, cusNo, cusPhone, driNm, calan, zip);
                //  JOptionPane.showMessageDialog(null,"Sorry");
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Sorry..");
            }

        }


    }//GEN-LAST:event_addBtnActionPerformed

    private void pNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameFieldActionPerformed
        // TODO add your handling code here:
        
            String  a=pNameField.getSelectedItem().toString();
            if(a.equals("Product")){
            searchF.setText(null);
            
            }else{
        searchF.setText(a);
            }
        
        
    }//GEN-LAST:event_pNameFieldActionPerformed

public void SearchAllCustomer(){

        String select=pNameField.getSelectedItem().toString();
        String a="ID";
        String name=searchF.getText();
        if(select.equals(a)){
       int x=JOptionPane.showConfirmDialog(rootPane, "Sure Show All Data...");
                if(x==0){
                       
            try {
                //JOptionPane.showConfirmDialog(rootPane, "Sure Show All Data...");

                this.dispose();
                DataBase db = new DataBase();
                db.showAllProductB();
               // JOptionPane.showMessageDialog(null, "Allll...!");
            } catch (SQLException ex) {
                Logger.getLogger(BtotalMalKinartStock.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        }else{    
            
            
                int x=JOptionPane.showConfirmDialog(rootPane, "Sure Show All Data...");
                if(x==0){
                       
            try {
     
                this.dispose();
                DataBase db = new DataBase();
                db.showAllProductB();
                //JOptionPane.showMessageDialog(null, "Allll...!");
            } catch (SQLException ex) {
                Logger.getLogger(BtotalMalKinartStock.class.getName()).log(Level.SEVERE, null, ex);
            }

                }
//ID BA NAME JAI HOK ALL SEARCH HOBE
        
        }
}
                  
public void SearchAllCustomerOneDate(){
    
            String aD = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String bD = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
        
        String name=searchF.getText();
        String select=pNameField.getSelectedItem().toString();
        String a="ID";
   //JOptionPane.showMessageDialog(null, "SearchAllCustomerOneDate() ");

        if(select.equals(a)){
        
   // JOptionPane.showMessageDialog(null, "ALL SEarch For Null      By ID....");

            try {
                this.dispose();
                DataBase db = new DataBase();
                db.showSelectProductOneDateALL(name,aD);
                
            } catch (SQLException ex) {
                Logger.getLogger(CcustomerStock.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
        
         
            try {
                this.dispose();
                DataBase db = new DataBase();
                db.showSelectProductOneDateALL(name,aD);
                
            } catch (SQLException ex) {
                Logger.getLogger(CcustomerStock.class.getName()).log(Level.SEVERE, null, ex);
            }
        
  
        }
        //ID BA NAME FOR ONE DATE SEARCH ALL
}

public void SearchAllCustomerTwoDate(){
            String aD = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String bD = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
        
        String name=searchF.getText();
        String select=pNameField.getSelectedItem().toString();
        String a="ID";
   /// JOptionPane.showMessageDialog(null, "xxxxxxxxxxSearchAllCustomerTwoDate() ");

        if(select.equals(a)){
                    try {
                this.dispose();
                DataBase db = new DataBase();
                db.showSelectProductTwoDateALL(name,aD,bD);
                
    //            JOptionPane.showMessageDialog(null, "ALL SEarch For Null   by NAme");
            } catch (SQLException ex) {
                Logger.getLogger(CcustomerStock.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        }else{
        
                     try {
                this.dispose();
                DataBase db = new DataBase();
                db.showSelectProductTwoDateALL(name,aD,bD);
                
  //              JOptionPane.showMessageDialog(null, "ALL SEarch For Null   by NAme");
            } catch (SQLException ex) {
                Logger.getLogger(CcustomerStock.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        }
        //ID BA NAME JAI HOK TWO DATE ER MAJER SAOB ASHBE
}

public void SearchAllCustomerByOnlyName(){
String aD = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String bD = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
        
        String name=searchF.getText();
        String select=pNameField.getSelectedItem().toString();
        String a="ID";
   
//JOptionPane.showMessageDialog(null, "SearchAllCustomerByOnlyName() ");

        if(select.equals(a)){
     try {

                this.dispose();
                DataBase db = new DataBase();
                db.showSelectProductB(name);
            } catch (SQLException ex) {
                Logger.getLogger(AMalBickriStock.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
             try {

                //String amount = quantityField.getText();
                this.dispose();
                DataBase db = new DataBase();
                db.showSelectProductB(name);
            } catch (SQLException ex) {
                Logger.getLogger(AMalBickriStock.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        }

}
            
             
public void SearchAllCustomerByOnlyNameAndOneDate(){

            String aD = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String bD = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
        
        String name=searchF.getText();
        String select=pNameField.getSelectedItem().toString();
        String a="ID";
//JOptionPane.showMessageDialog(null, "SearchAllCustomerOneDate() ");

        if(select.equals(a)){
        
//JOptionPane.showMessageDialog(null, "ALL SEarch For Null      By ID....");

            try {
                this.dispose();
                DataBase db = new DataBase();
                db.SearchCustomerByOneDateAndName(name,aD);
                
            } catch (SQLException ex) {
                Logger.getLogger(CcustomerStock.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
        
         
            try {
                this.dispose();
                DataBase db = new DataBase();
                db.SearchCustomerByOneDateAndName(name,aD);
                
            } catch (SQLException ex) {
                Logger.getLogger(CcustomerStock.class.getName()).log(Level.SEVERE, null, ex);
            }
        
  
        }
}

public void SearchAllCustomerByOnlyNameAndTwoDate(){

            String aD = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String bD = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
        
        String name=searchF.getText();
        String select=pNameField.getSelectedItem().toString();
        String a="ID";
    JOptionPane.showMessageDialog(null, "vvvvvvvvvvvSearchAllCustomerTwoDate() ");

        if(select.equals(a)){
        
        
            try {
                this.dispose();
                DataBase db = new DataBase();
                db.showSelectProductTwoDateALL(name,aD,bD);
                
                JOptionPane.showMessageDialog(null, "ALL SEarch For Null   by NAme");
            } catch (SQLException ex) {
                Logger.getLogger(CcustomerStock.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        }else{
        
         
        
            try {
                this.dispose();
                DataBase db = new DataBase();
                db.showSelectProductTwoDateALL(name,aD,bD);
                
                JOptionPane.showMessageDialog(null, "ALL SEarch For Null   by NAme");
            } catch (SQLException ex) {
                Logger.getLogger(CcustomerStock.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        }
}
            
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

            String aD = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String bD = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
        String s = new String("Product");
        String s1 = new String("");
        String a = searchF.getText();
        
                String name = searchF.getText();
        String am = quantityField.getText();
        String namTemp=searchF.getText();
        
            if(namTemp.equals("") && aD.equals("") && bD.equals("")){
            SearchAllCustomer();
            
            
            }else if(namTemp.equals("") && aD!="" && bD.equals("")){
            SearchAllCustomerOneDate();
            
            }else if(namTemp.equals("") &&aD!=""&&bD!=""){
            SearchAllCustomerTwoDate();
            
            
            }else if(namTemp!="" && aD.equals("") && bD.equals("")){
            SearchAllCustomerByOnlyName();
            
            
            }else if(namTemp!=""&& aD!="" && bD.equals("") ){
            SearchAllCustomerByOnlyNameAndOneDate();
            
            
            }else if(namTemp!="" && aD!="" && bD!=""){
            
            SearchAllCustomerByOnlyNameAndTwoDate();
            
            }
            else{
            
            JOptionPane.showMessageDialog(null, "OKKKK");
            
            }
            
      
            
            
            
            
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String id = idL.getText();
        String name = pNameField.getSelectedItem().toString();
        String amount = quantityField.getText();
        String date = ((JTextField) dateField.getDateEditor().getUiComponent()).getText();
            //  this.dispose();
        //    DataBase ob=new DataBase();
        //     ob.updateMainDate(id,name,amount,date);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void stockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTableMouseClicked
        // TODO add your handling code here:

        TableModel model = stockTable.getModel();
        int index[] = stockTable.getSelectedRows();
        Object[] row = new Object[10];
        // AtotalProductStock page=new AtotalProductStock();

          //DefaultTableModel model2=page.memoTable.getModel();
        //DefaultTableModel m2 = (DefaultTableModel).stockTable.getModel();
        for (int i = 0; i < index.length; i++) {

            row[0] = model.getValueAt(index[i], 0);
             row[1] = model.getValueAt(index[i], 1);
         
            System.out.println("OOKK" + (String) row[1]);
           
            row[2] = model.getValueAt(index[i], 2);
            row[3] = model.getValueAt(index[i], 3);
            row[4] = model.getValueAt(index[i], 4);
            row[5] = model.getValueAt(index[i], 5);
            row[6] = model.getValueAt(index[i], 6);
            row[7] = model.getValueAt(index[i], 7);
                 
            row[8] = model.getValueAt(index[i], 8);
            
            row[9] = model.getValueAt(index[i], 9);
            idL.setText((String) row[9]);
             String ab=f.getText();
          
           
        
           
          
           
            ((JTextField) dateField.getDateEditor().getUiComponent()).setText((String) row[0]);
           pNameField.setSelectedItem(row[1]);
         
           quantityField.setText((String) row[2]);
            c_nam.setText((String) row[3]);
               c_no.setText(((String) row[4]));
            c_phone.setText((String) row[5]);
            driver.setText((String) row[6]);
             calan_no.setText((String) row[7]);
          gari_no.setText((String) row[8]);
         //  f.setText();
       double temp = Double.parseDouble(quantityField.getText());
           if(temp==0){
           f.setText("0");
           }
            
     
           
            
  
           
         

        }

    }//GEN-LAST:event_stockTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
        
        String ab=f.getText();
             if(ab.equals("")){
           JOptionPane.showMessageDialog(null, "Sorry You Don't Delete This Item....!");
           
           
           }
             else if(ab.equals("0")){
                 
            try {
               // JOptionPane.showMessageDialog(null, "HOBEEEE.!");
                String name = pNameField.getSelectedItem().toString();
                
                String amount = quantityField.getText();
                String date = ((JTextField) dateField.getDateEditor().getUiComponent()).getText();
                String cusNm = c_nam.getText();
                String cusNo = c_no.getText();
                String cusPhone = c_phone.getText();
                String driNm = driver.getText();
                String calan = calan_no.getText();
                String zip = gari_no.getText();
                String id = idL.getText();
                  this.dispose();
                DataBase ob = new DataBase();
                ob.updateDataBDeleteZero(id, name, amount, date, cusNm, cusNo, cusPhone, driNm, calan, zip);
            } catch (SQLException ex) {
                Logger.getLogger(BtotalMalKinartStock.class.getName()).log(Level.SEVERE, null, ex);
            }
             
             }
           else{
             
              try {
            // TODO add your handling code here:

            String name = pNameField.getSelectedItem().toString();

            String amount = quantityField.getText();
            String date = ((JTextField) dateField.getDateEditor().getUiComponent()).getText();
            String cusNm = c_nam.getText();
            String cusNo = c_no.getText();
            String cusPhone = c_phone.getText();
            String driNm = driver.getText();
            String calan = calan_no.getText();
            String zip = gari_no.getText();
            String id = idL.getText();
            //  this.dispose();
            DataBase ob = new DataBase();
            ob.updateDataB(id, name, amount, date, cusNm, cusNo, cusPhone, driNm, calan, zip);
        } catch (SQLException ex) {
            Logger.getLogger(BtotalMalKinartStock.class.getName()).log(Level.SEVERE, null, ex);
        }
             
             }
        
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
            try {
            // TODO add your handling code here:
            this.dispose();
            DataBase x=new DataBase();
            x.searcgMemeoID();
             //  x.searcgMemeoID();
            
           // cashMemo ob = new cashMemo();
           // ob.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(allInfo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        BtotalMalKinartStock ob = new BtotalMalKinartStock();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        AMalBickriStock ob = new AMalBickriStock();
        ob.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        try {
            // TODO add your handling code here:
            this.dispose();
            CcustomerStock ob = new CcustomerStock();
            ob.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(BtotalMalKinartStock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        newEmployee ob = new newEmployee();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        // TODO add your handling code here:
        this.dispose();
        DAmalikerJomaKoroch ob=new DAmalikerJomaKoroch();
        ob.setVisible(true);

    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
        // TODO add your handling code here:
        this.setState(allInfo.ICONIFIED);

    }//GEN-LAST:event_jMenu15MouseClicked

    private void jMenu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu16MouseClicked

        System.exit(WIDTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu16MouseClicked

    private void jMenu16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu16ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu16ActionPerformed

    private void jMenu18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu18MouseClicked
        // TODO add your handling code here:
         PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {

                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.70, 1.24);
                printLabel.print(g2);
                return Printable.PAGE_EXISTS;

            }

        });
        boolean ok = job.printDialog();
        if (ok) {

            try {
                job.print();
            } catch (Exception e) {
            }
        }
        
        
    }//GEN-LAST:event_jMenu18MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        // TODO add your handling code here:
        
        this.dispose();
       allInfo ob=new allInfo();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked

        this.dispose();
        AESalaryPage ob=new  AESalaryPage();
        ob.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
                this.dispose();
        AESalaryPage ob=new  AESalaryPage();
        ob.setVisible(true);

        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BtotalMalKinartStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BtotalMalKinartStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BtotalMalKinartStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BtotalMalKinartStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BtotalMalKinartStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private com.toedter.calendar.JDateChooser aDate;
    private javax.swing.JButton addBtn;
    private com.toedter.calendar.JDateChooser bDate;
    private javax.swing.JTextField c_nam;
    private javax.swing.JTextField c_no;
    private javax.swing.JTextField c_phone;
    private javax.swing.JTextField calan_no;
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JTextField driver;
    javax.swing.JLabel f;
    private javax.swing.JTextField gari_no;
    javax.swing.JLabel idL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox pNameField;
    private javax.swing.JPanel printLabel;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTextField searchF;
    javax.swing.JTable stockTable;
    javax.swing.JTextField totalF;
    // End of variables declaration//GEN-END:variables
}
