/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author redoy
 */
public class DAmalikerJomaKoroch extends javax.swing.JFrame {

    java.util.Date x;
    java.sql.Date sqlD;

    /**
     * Creates new form malikerJomaKoroch
     */
    public DAmalikerJomaKoroch() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        printLabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        malikTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        searchF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        totalK = new javax.swing.JTextField();
        totalG = new javax.swing.JTextField();
        aDate = new com.toedter.calendar.JDateChooser();
        bDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        nameF = new javax.swing.JComboBox();
        Date = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        checkBtn = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        printLabel.setBackground(new java.awt.Color(204, 204, 204));

        malikTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Nam", "Joma", "Koroch", "Ki Babot", "K Nise"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(malikTable);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Joma");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Koroch");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Baki  TK");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Maliker joma Koroch");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        totalK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalK.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        totalG.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalG.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        aDate.setDateFormatString("yyyy-MM-dd");

        bDate.setDateFormatString("yyyy-MM-dd");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("From");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("To");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Shajalal Stone Crusher");

        javax.swing.GroupLayout printLabelLayout = new javax.swing.GroupLayout(printLabel);
        printLabel.setLayout(printLabelLayout);
        printLabelLayout.setHorizontalGroup(
            printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printLabelLayout.createSequentialGroup()
                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, printLabelLayout.createSequentialGroup()
                            .addGap(334, 334, 334)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(printLabelLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(printLabelLayout.createSequentialGroup()
                                        .addComponent(totalG, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(totalK, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(139, 139, 139)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(printLabelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(printLabelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(aDate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bDate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLabelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchF, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        printLabelLayout.setVerticalGroup(
            printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(2, 2, 2)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 22, 130, 0));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name");
        jLabel5.setToolTipText("");
        jLabel5.setFocusable(false);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        amountField.setBackground(new java.awt.Color(204, 204, 204));
        amountField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountField.setText("0.0");
        amountField.setBorder(null);
        amountField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amountFieldMouseClicked(evt);
            }
        });
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        jPanel4.add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 120, 20));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, 10));

        nameF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Md Joynal Abeedin", "Md Sobuj Miah", "All" }));
        nameF.setBorder(null);
        nameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFActionPerformed(evt);
            }
        });
        jPanel4.add(nameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 220, 30));

        Date.setDateFormatString("yyyy-MM-dd");
        Date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Date:");
        jLabel4.setToolTipText("");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 110, 30));

        checkBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkBtn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Joma", "Newa", "Others" }));
        checkBtn.setBorder(null);
        jPanel4.add(checkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 30));

        jLabel3.setText("TK");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 80, 30, 20));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("OVER ALL KOROCH");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managementsystem/patner.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(printLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(45, 45, 45)
                .addComponent(jLabel11)
                .addGap(49, 49, 49)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addComponent(printLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu2.setText("                                                                                                ");
        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(204, 0, 204));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu4.setText("Sale Product");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("                     ");
        jMenuBar1.add(jMenu6);

        jMenu5.setText("Stock");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        jMenuItem1.setText("    Mal Kiner Stock    ");
        jMenuItem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem3.setText("  Mal Bickri Stock            ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        jMenu7.setBackground(new java.awt.Color(255, 255, 255));
        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setText("                  ");
        jMenuBar1.add(jMenu7);

        jMenu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu9.setText("   Customer Stock       ");
        jMenu9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu8.setText("                    ");
        jMenuBar1.add(jMenu8);

        jMenu11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu11.setText("Employee Details");
        jMenu11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem2.setText("Add New Employee");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem2);
        jMenu11.add(jSeparator1);

        jMenuItem4.setText("Salary");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem4);

        jMenuBar1.add(jMenu11);

        jMenu10.setText("          Daily Koroch         ");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        jMenu12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu12.setText("Owener Details");
        jMenu12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu12);

        jMenu17.setText("     ALL INFO        ");
        jMenu17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu17MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu17);

        jMenu18.setText("      Print       ");
        jMenu18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu18MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu18);

        jMenu15.setBorder(null);
        jMenu15.setText("-");
        jMenu15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu15);

        jMenu16.setBorder(null);
        jMenu16.setForeground(new java.awt.Color(204, 0, 0));
        jMenu16.setText("X");
        jMenu16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu16MouseClicked(evt);
            }
        });
        jMenu16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu16ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu16);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String s = new String("Joma");

        String s1 = new String("Newa");
        String s2 = new String("Select");
        String AB = amountField.getText();
        String a = checkBtn.getSelectedItem().toString();
        String name = nameF.getSelectedItem().toString();
        if (AB.equals("") || AB.equals("0.0") || ((JTextField) Date.getDateEditor().getUiComponent()).getText().equals("")) {

            if (AB.equals("") || AB.equals("0.0")) {
                JOptionPane.showMessageDialog(null, "Enter Taka...");
            } else {
                JOptionPane.showMessageDialog(null, "Enter Date...");

            }

        } else {

            double amx = Double.parseDouble(amountField.getText());
            if (amx <= 0 || amountField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter TK AND Correct Format......");

            } else {

                if (s.equals(a) && name.equals("Md Joynal Abeedin") && name != "Select") {
                     int dialogButton =JOptionPane.showConfirmDialog (null, "Sure TK Joma Ditaysen Joynal Abeedin...??","Warning",JOptionPane.YES_NO_OPTION);

            if (dialogButton == 0) { //The ISSUE is here

                    //JOptionPane.showMessageDialog(null, "Joma");
                    try {
                        // TODO add your handling code here:

                        String nam = nameF.getSelectedItem().toString();

                        String am = amountField.getText();
                        x = Date.getDate();
                        sqlD = new java.sql.Date(x.getTime());

                        //this.dispose();
                        DataBase ob = new DataBase();
                        ob.mainMalikStock(nam, am, sqlD);
                        ob.mainMalikStockJomaHitTotalTk(nam, am, sqlD);
                    } catch (SQLException ex) {

                    }
            }

                } else if (s.equals(a) && name.equals("Md Sobuj Miah") && name != "Select") {
             //       JOptionPane.showMessageDialog(null, "Joma 2");
                          int dialogButton =JOptionPane.showConfirmDialog (null, "Sure TK Joma Ditaysen Sobuj Miah...??","Warning",JOptionPane.YES_NO_OPTION);

            if (dialogButton == 0) { //The ISSUE is here


                    try {
                        // TODO add your handling code here:

                        String nam = nameF.getSelectedItem().toString();

                        String am = amountField.getText();
                        x = Date.getDate();
                        sqlD = new java.sql.Date(x.getTime());

                        //  this.dispose();
                        DataBase ob = new DataBase();
                        ob.mainMalikStock(nam, am, sqlD);
                        ob.mainMalikStockJomaHitTotalTk(nam, am, sqlD);

                    } catch (SQLException ex) {

                    }
            }
                    /*
                     try {
                     // TODO add your handling code here:

                     String nam=nameField.getText();
                     String number=noField.getText();
                     String am=amountField.getText();
                     String date =((JTextField)dateField.getDateEditor().getUiComponent()).getText();

                     this.dispose();
                     DataBase ob=new DataBase();
                     ob.malik2(nam,number,am,date);
                     } catch (SQLException ex) {
                     Logger.getLogger(malikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     */
                } else if (s1.equals(a) && name.equals("Md Joynal Abeedin") && name != "Select") {
                  //  JOptionPane.showMessageDialog(null, "NEWA");
                 int dialogButton =JOptionPane.showConfirmDialog (null, "Sure TK Nitaysen  Joynal Abeedin........??","Warning",JOptionPane.YES_NO_OPTION);

            if (dialogButton == 0) { //The ISSUE is here

                    
                    
                    try {
                        // TODO add your handling code here:

                        String nam = nameF.getSelectedItem().toString();

                        String am = amountField.getText();
                        x = Date.getDate();
                        sqlD = new java.sql.Date(x.getTime());
                        // this.dispose();
                        DataBase ob = new DataBase();
                        ob.mainMalikStockNewa(nam, am, sqlD);
                        ob.mainMalikStockNewaHitTotalTk(nam, am, sqlD);

                    } catch (SQLException ex) {

                    }

     
    }else{
    
    
    }
                
                
                
                } else if (s1.equals(a) && name.equals("Md Sobuj Miah") && name != "Select") {
                          int dialogButton =JOptionPane.showConfirmDialog (null, "Sure TK Nitaysen Sobuj Miah...???","Warning",JOptionPane.YES_NO_OPTION);

            if (dialogButton == 0) { //The ISSUE is here
                try {
                        // TODO add your handling code here:

                        String nam = nameF.getSelectedItem().toString();

                        String am = amountField.getText();
                        x = Date.getDate();
                        sqlD = new java.sql.Date(x.getTime());
                        // this.dispose();
                        DataBase ob = new DataBase();

                        ob.mainMalikStockNewa(nam, am, sqlD);

                        ob.mainMalikStockNewaHitTotalTk(nam, am, sqlD);

                    } catch (SQLException ex) {

                    }
                    /*
                     try {
                     // TODO add your handling code here:

                     String nam=nameField.getText();
                     String number=noField.getText();
                     String am=amountField.getText();
                     String date =((JTextField)dateField.getDateEditor().getUiComponent()).getText();

                     this.dispose();
                     DataBase ob=new DataBase();
                     ob.malik2(nam,number,am,date);
                     } catch (SQLException ex) {
                     Logger.getLogger(malikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     */

                } else {
                    JOptionPane.showMessageDialog(null, "SORRYYY");
                }

            }
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void amountFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amountFieldMouseClicked
        // TODO add your handling code here:
        amountField.setText("");
    }//GEN-LAST:event_amountFieldMouseClicked

    private void nameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFActionPerformed
        // TODO add your handling code here:
        String a = nameF.getSelectedItem().toString();
        searchF.setText(a);


    }//GEN-LAST:event_nameFActionPerformed
    public void ShowDataFromTO() {

        try {

            String fDate = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String tDate = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();

            this.dispose();
            DataBase db = new DataBase();
            db.SearchFromToMalik(fDate, tDate);
        } catch (SQLException ex) {
            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void ShowDataFromOnlyOneDate() {

        try {

            String fDate = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String tDate = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();

            this.dispose();
            DataBase db = new DataBase();
            db.SearchFromToMalikOneDate(fDate);
        } catch (SQLException ex) {
            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void ShowTotalDataAllInfo() {
        try {

            String fDate = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String tDate = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();

            this.dispose();
            DataBase db = new DataBase();
            db.SearchDataALLTotal(fDate, tDate);
        } catch (SQLException ex) {
            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void ShowDataFromToMalik() {

        try {

            String fDate = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String tDate = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
            String name = searchF.getText();
            this.dispose();
            DataBase db = new DataBase();
            db.SearchDataFromToTotalMalik(fDate, tDate, name);
        } catch (SQLException ex) {
            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void ShowDataOneDateAndNameMalik() {

        try {

            String fDate = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();
            String name = searchF.getText();
            String tDate = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();

            this.dispose();
            DataBase db = new DataBase();
            db.SearchDataFromToTotal(fDate, tDate, name);
        } catch (SQLException ex) {
            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void ShowTotalDataFromToAllInfo() {
        try {
  // ShowTotalDataFromToAllInfo();
            String fDate = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();

            String tDate = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();

            this.dispose();
            DataBase db = new DataBase();
            db.SearchDataFromToTotal(fDate, tDate);
        } catch (SQLException ex) {
            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String s = new String("Select");
        String s1 = new String("All");
        String s3 = new String("");
        String a = searchF.getText();
        String temp = "Maliker joma Koroch";
        //  String am = quantityField.getText();

        if (jLabel1.getText().equals("Maliker joma Koroch")) {
      //  jLabel1.setText("");

            if (s.equals(a)) {

                String y = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();
                String z = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
                if (a.equals("") && z.equals("") && y.equals("")) {

                    JOptionPane.showMessageDialog(null, "Select  Name...!");
                    //searchF.setText(null)
                } else {

                    JOptionPane.showMessageDialog(null, "Allll...!");

                    ShowDataFromTO();
                }

            } else if (s1.equals(a)) {
                try {

                    String ab = "";
                    String x = searchF.getText();
                    String y = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();
                    String z = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
                    String tempDate = ((JTextField) Date.getDateEditor().getUiComponent()).getText();

                    String date = searchF.getText();
                    if (searchF.getText().equals(s1) && z.equals("") && y.equals("")) {
                 //       //s1=all
                   //     JOptionPane.showMessageDialog(null, "ALL ..");
                        this.dispose();
                        DataBase db = new DataBase();
                        db.showAllProductD();
                        //  JOptionPane.showMessageDialog(null, "Allll...!");
                    } else if (searchF.getText().equals(s1) && y != "" && z.equals(ab)) {
                        //OK
                     //   JOptionPane.showMessageDialog(null, "Allll one date...!");
                        ShowDataFromOnlyOneDate();
                    } else if (searchF.getText().equals(s1) && z != "" && y != "") {
                       /// JOptionPane.showMessageDialog(null, "xAllll From To  DAtE...!");
                        ShowDataFromTO();

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(BtotalMalKinartStock.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {

            //    JOptionPane.showMessageDialog(null, "MMALL ..");
                String x = searchF.getText();
                String y = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();
                String z = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
                String tempDate = ((JTextField) Date.getDateEditor().getUiComponent()).getText();
                String ab = "";
                String date = searchF.getText();

                if (x.equals(nameF.getSelectedItem().toString())) {

          //          JOptionPane.showMessageDialog(null, "MALIK");
                    if (z.equals("") && y.equals("")) {
                        try {
                            //s1=all
                          //  JOptionPane.showMessageDialog(null, "ALL ..");
                            this.dispose();
                            DataBase db = new DataBase();
                            db.showAllProductDSelectMalik(x);
                            //  JOptionPane.showMessageDialog(null, "Allll...!");
                        } catch (SQLException ex) {
                            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else if (y != "" && z.equals(ab)) {
                        try {
                            //OK
                            ///JOptionPane.showMessageDialog(null, "Allll one date...!");
                            this.dispose();
                            DataBase db = new DataBase();
                            db.ShowMalikDataFromOneDateAndName(x, y);
                        } catch (SQLException ex) {
                            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else  {
                        try {
                      //      JOptionPane.showMessageDialog(null, "Allll From To  DAtE...!");
                            this.dispose();
                            DataBase db = new DataBase();
                           db.ShowMalikDataFromTwoDateAndName(x, y, z);
                        } catch (SQLException ex) {
                            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                } else if (x.equals("")) {
                    
                    
                      //   JOptionPane.showMessageDialog(null, "Allll FC<MNNNNNrom To  DAtE...!");
                       
                   
                if (x.equals(ab)) {

           //         JOptionPane.showMessageDialog(null, "NULLL");
                    if (z.equals("") && y.equals("")) {
                        try {
                            //s1=all
                        //    JOptionPane.showMessageDialog(null, "ALL ..");
                            this.dispose();
                            DataBase db = new DataBase();
                            db.showAllProductDSelectMalik(x);
                            //  JOptionPane.showMessageDialog(null, "Allll...!");
                        } catch (SQLException ex) {
                            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else if (y != "" && z.equals(ab)) {
                        try {
                            //OK
             //               JOptionPane.showMessageDialog(null, "Allll one date...!");
                            this.dispose();
                            DataBase db = new DataBase();
                            db.ShowMalikDataFromOneDateAndName(x, y);
                        } catch (SQLException ex) {
                            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else  {
                        try {
               //             JOptionPane.showMessageDialog(null, "xxxxxxxxxxxxxxxxxxxxxAllll From To  DAtE...!");
                            this.dispose();
                            DataBase db = new DataBase();
                           db.ShowMalikDataFromTwoDateAndName(x, y, z);
                        } catch (SQLException ex) {
                            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
 
                    
                }

                /**
                 * *************************************************************************
                 */
                /*
             
                 if(x!="" && z=="" && y!=""){
                 //Select, Md Joynal Abeedin, Md Sobuj Miah, All                    
                 //  ShowDataOneDateAndNameMalik();
                    
                 JOptionPane.showMessageDialog(null, "XX");
                 }else if(z!=""&& z!="" && y!=""){
                 //Select, Md Joynal Abeedin, Md Sobuj Miah, All                    
                    
                 JOptionPane.showMessageDialog(null, "YY");
                 ShowDataFromToMalik();
                    
                 }else if(x!=""&& y.equals("")&&z.equals("")){
                    
                 JOptionPane.showMessageDialog(null, "ZZ");
                 try {

                 String name = searchF.getText();
                 //String amount = quantityField.getText();
                 this.dispose();
                 DataBase db = new DataBase();
                 db.showSelectMalikD(name);
                 } catch (SQLException ex) {
                 Logger.getLogger(AMalBickriStock.class.getName()).log(Level.SEVERE, null, ex);
                 }

                 }
        
            
                 */
            }

            /**
             * *****************************************************************?//////
             * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
             */
            }
        } else if (jLabel1.getText().equals("Mill's All Information")) {
        //    jLabel1.setText("Maliker joma Koroch");

 //       JOptionPane.showMessageDialog(null,"Mill's All InformationXXXXXX");
            String y = ((JTextField) aDate.getDateEditor().getUiComponent()).getText();
            String z = ((JTextField) bDate.getDateEditor().getUiComponent()).getText();
            String tempDate = ((JTextField) Date.getDateEditor().getUiComponent()).getText();

            if (searchF.getText().equals("All")) {

                ShowTotalDataAllInfo();
                //JOptionPane.showMessageDialog(null, "Mill's All ");

            } else if (searchF.getText().equals("") && z != "" && y != "") {
                ShowTotalDataFromToAllInfo();
              //  JOptionPane.showMessageDialog(null, "Mill's DATEz");

            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        try {
            // TODO add your handling code here:
            this.dispose();
            DataBase x=new DataBase();
            x.searcgMemeoID();  
        //    x.searcgMemeoID();
        } catch (SQLException ex) {
            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        BtotalMalKinartStock ob = new BtotalMalKinartStock();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        AMalBickriStock ob = new AMalBickriStock();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        try {
            // TODO add your handling code here:
            this.dispose();
            CcustomerStock ob = new CcustomerStock();
            ob.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        newEmployee ob = new newEmployee();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        // TODO add your handling code here:
        this.dispose();
        DAmalikerJomaKoroch ob = new DAmalikerJomaKoroch();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu18MouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {

                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.70, 1.20);
                printLabel.print(g2);
                return Printable.PAGE_EXISTS;

            }

        });
        boolean ok = job.printDialog();
        if (ok) {

            try {
                job.print();
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jMenu18MouseClicked

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
        // TODO add your handling code here:
        this.setState(allInfo.ICONIFIED);
    }//GEN-LAST:event_jMenu15MouseClicked

    private void jMenu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu16MouseClicked

        System.exit(WIDTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu16MouseClicked

    private void jMenu16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu16ActionPerformed

    private void jMenu17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu17MouseClicked
        // TODO add your handling code here:
        this.dispose();
        allInfo ob = new allInfo();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenu17MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
DefaultTableModel m = (DefaultTableModel) malikTable.getModel();
   
        if (jLabel1.getText().equals("Maliker joma Koroch")) {
            jLabel1.setText("Mill's All Information");
            m.setRowCount(0);
        } else if (jLabel1.getText().equals("Mill's All Information")) {
            jLabel1.setText("Maliker joma Koroch");
            m.setRowCount(0);
     
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        // TODO add your handling code here:
        
        
        this.dispose();
        
        dailyKoroch ob=new dailyKoroch();
        ob.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
            this.dispose();
            AESalaryPage ob=new AESalaryPage();
            ob.setVisible(true);
        


// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        AESalaryPage ob=new  AESalaryPage();
        ob.setVisible(true);
 
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAmalikerJomaKoroch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DAmalikerJomaKoroch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date;
    private com.toedter.calendar.JDateChooser aDate;
    private javax.swing.JTextField amountField;
    private com.toedter.calendar.JDateChooser bDate;
    private javax.swing.JComboBox checkBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    javax.swing.JTable malikTable;
    private javax.swing.JComboBox nameF;
    private javax.swing.JPanel printLabel;
    private javax.swing.JTextField searchF;
    javax.swing.JTextField total;
    javax.swing.JTextField totalG;
    javax.swing.JTextField totalK;
    // End of variables declaration//GEN-END:variables

}
