/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author redoy
 */
public class newEmployee extends javax.swing.JFrame {

    /**
     * Creates new form newEmployee
     */
    public newEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        dgnField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fatherNameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mobileField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        addField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dateField = new com.toedter.calendar.JDateChooser();
        sexField = new javax.swing.JComboBox();
        idField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        savedBtn = new javax.swing.JButton();
        pc = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        dateField1 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        deleteBtn1 = new javax.swing.JButton();
        idx = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dgnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dgnFieldActionPerformed(evt);
            }
        });
        jPanel4.add(dgnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Designation");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 105, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText(" Name");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 120, 30));
        jPanel4.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Father's Name");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 224, 105, 20));
        jPanel4.add(fatherNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 170, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Sex");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 105, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Sallary");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 105, 24));

        salaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryFieldActionPerformed(evt);
            }
        });
        jPanel4.add(salaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Mobile No:");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 105, 24));

        mobileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileFieldActionPerformed(evt);
            }
        });
        jPanel4.add(mobileField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 170, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Present Address:");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 105, 24));

        addField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFieldActionPerformed(evt);
            }
        });
        jPanel4.add(addField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 170, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Joining Date");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 105, 30));

        dateField.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 166, 30));

        sexField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gender", "Male", "Female", "Other's" }));
        jPanel4.add(sexField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 30));

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        jPanel4.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Employee ID");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 140, 110, 24));

        savedBtn.setText("Add Employee");
        savedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedBtnActionPerformed(evt);
            }
        });
        jPanel4.add(savedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 140, -1));
        jPanel4.add(pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 58, 31));

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });
        jPanel4.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 186, 29));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 132, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Birth Day");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 110, 24));

        dateField1.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(dateField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 170, 30));

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 150, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel4.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 150, -1));

        deleteBtn1.setText("Clear");
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });
        jPanel4.add(deleteBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 160, -1));
        jPanel4.add(idx, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 87, 85, 26));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(925, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 990, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Shajalal Stone Crosher Employee Details");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 440, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managementsystem/Labor Icon.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 640, 540));

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jMenu2.setText("                                                         ");
        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(204, 0, 204));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu4.setText("Sale Product");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("          ");
        jMenuBar1.add(jMenu6);

        jMenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu5.setText("Customer Stock");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu7.setBackground(new java.awt.Color(255, 255, 255));
        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setText("          ");
        jMenuBar1.add(jMenu7);

        jMenu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu9.setText("                              ");
        jMenu9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu10.setBackground(new java.awt.Color(255, 255, 255));
        jMenu10.setForeground(new java.awt.Color(255, 255, 255));
        jMenu10.setText("          ");
        jMenuBar1.add(jMenu10);

        jMenu11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu11.setText("Employee Details");
        jMenu11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem2.setText("Add New Employee");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem2);

        jMenuItem1.setText("About Employee");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem1);

        jMenuBar1.add(jMenu11);

        jMenu14.setBackground(new java.awt.Color(255, 255, 255));
        jMenu14.setForeground(new java.awt.Color(255, 255, 255));
        jMenu14.setText("           ");
        jMenuBar1.add(jMenu14);

        jMenu12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu12.setText("Owener Details");
        jMenu12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu12);

        jMenu17.setText("                     ");
        jMenuBar1.add(jMenu17);

        jMenu18.setText("     All IFNO              ");
        jMenu18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu18MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu18);

        jMenu15.setBorder(null);
        jMenu15.setText("-");
        jMenu15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu15);

        jMenu16.setBorder(null);
        jMenu16.setForeground(new java.awt.Color(204, 0, 0));
        jMenu16.setText("X");
        jMenu16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu16MouseClicked(evt);
            }
        });
        jMenu16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu16ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu16);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dgnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dgnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dgnFieldActionPerformed

    private void salaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryFieldActionPerformed

    private void mobileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileFieldActionPerformed

    private void addFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFieldActionPerformed

    private void savedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedBtnActionPerformed
       String input=JOptionPane.showInputDialog("Enter Password For Add Employee...!");
       if(input.equals("add")){
       
        try {
            // TODO add your handling code here:
            String id = idField.getText();
            String name = nameField.getText();
            String father = fatherNameField.getText();
            String dg = dgnField.getText();
           String sex = sexField.getSelectedItem().toString();
           // String sex=salaryField.getText();
            String salary = salaryField.getText();
            String mobile = mobileField.getText();
            String address = addField.getText();
            String birthDate =((JTextField)dateField1.getDateEditor().getUiComponent()).getText();
            String joinDate =((JTextField)dateField.getDateEditor().getUiComponent()).getText();
            
            /*
                       if(salaryField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Enter Salary Amount.....!");
            }
                       */
            // String joinDate = joinField.getText();
            if(salaryField.getText().equals("") ||dg.equals("") ||mobile.equals("") ||id.equals("")){
                
            
           
            JOptionPane.showMessageDialog(null, "Enter All Inormation...!");
                    
            }else{
            
                       double salaryTemp=Double.parseDouble(salaryField.getText());
            
            if(salaryTemp<=0){
                
            JOptionPane.showMessageDialog(null, "Enter Correct TK...!");
                  
            }
            else if(salaryTemp>0){
                    
            DataBase db = new DataBase();
            db.insertImployee(id,name,father,dg,sex,salary,mobile,address,birthDate,joinDate);
          
                    
                    }
 
            }           

// String email = emailField.getText();
            // String image = picUploadBtn.getText();
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, "Enter All Inormation...!");
        }
        
       
       }else{
       JOptionPane.showMessageDialog(null, "Sorry...!");
       
       }
        
        
    }//GEN-LAST:event_savedBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      if(searchField.getText().equals("")){
      JOptionPane.showMessageDialog(null, "Entetr Any Name...!");
      }else{
      
        try {
                String ID = searchField.getText();
                DataBase db = new DataBase();
                this.dispose();
                db.searchStaff(ID);
            } catch (SQLException ex) {
                Logger.getLogger(newEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
      
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_searchFieldKeyTyped

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchFieldKeyReleased

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchFieldKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
       String input=JOptionPane.showInputDialog("Enter Password For delete Employee...!");
       if(input.equals("add")){
       
         try {
            // TODO add your handling code here:
            String id = idField.getText();
            String name = nameField.getText();
            String father = fatherNameField.getText();
            String dg = dgnField.getText();
           // String sex = sexField.toString();
            String sex= sexField.getSelectedItem().toString();
            String salary = salaryField.getText();
            String mobile = mobileField.getText();
            String address = addField.getText();
            String birthDate =((JTextField)dateField1.getDateEditor().getUiComponent()).getText();
            String joinDate =((JTextField)dateField.getDateEditor().getUiComponent()).getText();
            double salaryTemp=Double.parseDouble(salaryField.getText());
            
            if(salaryTemp<=0){
                
            JOptionPane.showMessageDialog(null, "Enter TK...!");
                  
            }
            // String joinDate = joinField.getText();
            else if(salaryField.getText().equals("") ||dg.equals("") ||mobile.equals("") ||id.equals("")){
                
            
            
            JOptionPane.showMessageDialog(null, "Enter All Inormation...!");
                    
            }else if(salaryTemp>0){
              
            DataBase db = new DataBase();
            db.updateImployee(id,name,father,dg,sex,salary,mobile,address,birthDate,joinDate);
            } // String email = emailField.getText();
            // String image = picUploadBtn.getText();
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, "Enter TK...!");
                  
        }
        
        
        
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
                                         
       String input=JOptionPane.showInputDialog("Enter Password For delete Employee...!");
       if(input.equals("delete")){
       
        
        
        try {
              String id=idx.getText();
               String name=nameField.getText();
               // String id = idField.getText();
                DataBase db = new DataBase();
               db.DeleteStuff(id,name);
                this.dispose();
            } catch (SQLException ex) {
                System.out.println("ERROR:" + ex);
            }
       }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        // TODO add your handling code here:
                   idField.setText("");
            nameField.setText("");
            fatherNameField.setText("");
            dgnField.setText("");
            pc.setText("");
            salaryField.setText("");
            mobileField.setText("");
            addField.setText("");
               ((JTextField)dateField1.getDateEditor().getUiComponent()).setText("");
            ((JTextField)dateField.getDateEditor().getUiComponent()).setText("");
        
    }//GEN-LAST:event_deleteBtn1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        allInfo ob=new allInfo();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
    try {
            // TODO add your handling code here:
            this.dispose();
            DataBase x=new DataBase();
            x.searcgMemeoID();
               //x.searcgMemeoID();
            
           // cashMemo ob = new cashMemo();
           // ob.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(allInfo.class.getName()).log(Level.SEVERE, null, ex);
        }      

    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        try {
            // TODO add your handling code here:
            this.dispose();
            CcustomerStock ob=new CcustomerStock();
            ob.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(newEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        newEmployee ob=new newEmployee();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.dispose();
        AESalaryPage ob=new AESalaryPage();
        ob.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
        // TODO add your handling code here:
        this.setState(allInfo.ICONIFIED);

    }//GEN-LAST:event_jMenu15MouseClicked

    private void jMenu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu16MouseClicked

        System.exit(WIDTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu16MouseClicked

    private void jMenu16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu16ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.dispose();
        DAmalikerJomaKoroch ob = new DAmalikerJomaKoroch();
        ob.setVisible(true);


    }//GEN-LAST:event_jMenu16ActionPerformed

    private void jMenu18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu18MouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        allInfo ob =new allInfo();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenu18MouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        // TODO add your handling code here:
        
        
        
        
        
        
    }//GEN-LAST:event_jMenu12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addField;
    private com.toedter.calendar.JDateChooser dateField;
    private com.toedter.calendar.JDateChooser dateField1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JTextField dgnField;
    private javax.swing.JTextField fatherNameField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idx;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField mobileField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel pc;
    private javax.swing.JTextField salaryField;
    private javax.swing.JButton savedBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox sexField;
    // End of variables declaration//GEN-END:variables
   void setEmployee(String a,String ID, String Nm, String fm, String dgn, String sex, String salary, String mobile, String address, String birthDate, String joinDate) {
 
  
            
            idx.setText(a);
            idField.setText(ID);
            nameField.setText(Nm);
            fatherNameField.setText(fm);
            dgnField.setText(dgn);
           // sexField.setSelectedItem("");
          //  sexField.setText(sex);box.getEditor().setItem("Text Has Changed");
          //  sexField.getEditor().setItem(sex);
             // sexField.setSelectedItem("text has changed");
           
            sexField.setSelectedItem(sex);
            salaryField.setText(salary);
            mobileField.setText(mobile);
            System.out.println("SEX"+sex);
            addField.setText(address);
               ((JTextField)dateField1.getDateEditor().getUiComponent()).setText(birthDate);
            ((JTextField)dateField.getDateEditor().getUiComponent()).setText(joinDate);
            /*
            
             System.out.println("Page");
            // idField.setText(emId);
             nameField.setText(nM);
            fatherNameField.setText(fN);
            dgnField.setText(deg);
            pc.setText(sex);
           // String sex = sexField.toString();
           // sexField.setToolTipText(sex);
           // String sex=salaryField.setText();
            salaryField.setText(salary);
            mobileField.setText(mobile);
             addField.setText(address);
           ((JTextField)dateField1.getDateEditor().getUiComponent()).setText(birthDate);
            ((JTextField)dateField.getDateEditor().getUiComponent()).setText(joinDate);
            
            
            
            */
    
    }
    
}
